apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-quota
  namespace: dev
spec:
  hard:
    # Максимум сколько ресурсов могут запросить ВСЕ поды в сумме
    requests.cpu: "500m"      # Половина одного ядра
    requests.memory: "1Gi"    # 1 Гигабайт памяти
    # Жесткий лимит, выше которого Кубер просто убьет под
    limits.cpu: "1"           # Одно ядро максимум
    limits.memory: "2Gi"      # 2 Гигабайта максимум
    # Максимальное количество подов в неймспейсе
    pods: "10"
